name: B

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened, edited]

jobs:
  github-example-branches:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
     - name: Get PR Info
       run: |
         echo "Title: ${{ github.event.pull_request.title }}"
         echo "Body: ${{ github.event.pull_request.body }}"
         echo "Head.label: ${{ github.event.pull_request.head.label }}"

     - name: List Artifacts
       run: |
         curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/badgerloop-software/sandbox/actions/artifacts?name=test-artifact

     - name: Get Artifact
       run: |
         curl -LO \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/badgerloop-software/sandbox/actions/artifacts/967408877/zip
         ls -l
         curl -LO \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/badgerloop-software/sandbox/actions/artifacts/967408877
         ls -l
         cat 9*
         cat zip
         unzip zip
         ls -l

  self-hosted-job:
    runs-on: self-hosted
    steps:
     - name: Show PR Info
       run: |
         echo "Title: ${{ github.event.pull_request.title }}"
         echo "Body: ${{ github.event.pull_request.body }}"
         echo "Head.label: ${{ github.event.pull_request.head.label }}"
         pwd

     - name: List Artifacts
       run: |
         curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/badgerloop-software/sandbox/actions/artifacts?name=test-artifact
         curl -LO \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/badgerloop-software/sandbox/actions/artifacts/967408877/zip
         ls -l
